@show_zxai:
    ARTICLE(@article_zxai)
return

@article_zxai:
data "zxai", 1
data @text_zxai_1

@text_zxai_1:
data 20
data "ZX Spectrum art generated by"
data "neural networks. Two models"
data "trained on thousands of ZX"
data "Spectrum images from zxart.ee:"
data "a DDPM (Denoising Diffusion"
data "Probabilistic Model) and a"
data "fine-tuned Stable Diffusion."
data "Both output images at native"
data "Spectrum resolution of 256x192."
data "Give it a text prompt like a"
data "cute cat, a solar system, a sea"
data "shore or a disco ball, and get"
data "back a picture that looks like"
data "it was pixel-crafted on a real"
data "Spectrum in 1985."
data "The models are on HuggingFace."
data "Because if AI is going to"
data "replace artists, it should"
data "start with pixel artists from"
data "the 80s."
